### PR TITLE
Fix bluejamesbond/TextJustify-Android#89

### PR DESCRIPTION
**Pull request by PouyaDarabi**
-remove change alignment on setReverse
-disable string reversing

### CODE REVIEW

**Comment by PouyaDarabi** [comment]
bug:

in TestActivity.java
text align was set to justify
but after that setReverse was called!
so with last code , text-align will set to right , and text will not be justify!

pic 1:



pic 2:

text was reversed! set last DefisReversed to false resolved this one



two changes!
bug fixed!

**Comment by bluejamesbond** [comment]
Thanks for the pics. I will merge when I get home and issue a new release.

**Comment by bluejamesbond** [comment]
Thank you

**Comment by bluejamesbond** [comment]
Released v2.1.1

**Pull request merged**
